### ISSUE TITLE
Default color palette for grouping variable is short

### ISSUE THREAD

**Issue by camilogarciabotero** [stemangiola/tidyHeatmap#51]
Hi there,

Thanks for working on `{tidyHeatmap}`, I've enjoyed it pretty much. I`ve been playing with it trying to set a categorical variable as a grouping variable, however, the number of color in the default palettes seems to be scarce for many variables and the variable names tend to be cross the variables' boxes as in this example:

![Screen Shot 2020-08-07 at 10 22 08 AM](https://user-images.githubusercontent.com/25586362/89661607-82d75480-d898-11ea-8573-a913c4279a83.png)

Is there a way to provide more colors and even more customization on this matter?

Thanks,
Camilo

**Comment by stemangiola** [comment]
Hola Camilo,

try the branch `improve-groupings-graphics` and let me know how you go.

For more customisation I have improved the documentation: `?heatmap`

Actually I was thinking to go the opposite direction, leaving all grouping white with black text, because the grouping colour is purely aesthetical, and not really functional, adding visual elements to the plot. What do you think?

**Comment by camilogarciabotero** [comment]
Hola Stefano, 

Thanks for your quick response and solution. The solution in the `improve-groupings-graphics` branch worked very well:

![Screen Shot 2020-08-09 at 4 11 40 PM](https://user-images.githubusercontent.com/25586362/89742099-81568980-da5c-11ea-88d2-2346843058c6.png)

Regarding your suggestion on removing color backgrounds and adding black text, I agree with you on leaving it black and white.

Thanks,
Camilo.
